#Introduction
I asked myself in my country what is the most used web apps and from a short survey i conducted, (amongst friends and family) i found out that it was e-commerce web apps.
Since now they constitute to helping make life easier i decided to take a look and develop more precise data for data scientist to analyse

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url = 'https://www.brandnav.io/reports/countries/ghana/'

page = requests.get(url)

soup = BeautifulSoup(page.content, 'html.parser')

In [ ]:
print(soup)

<!DOCTYPE html>

In [ ]:
soup.find('table')

<table><thead><tr><th id="rank" style="width:100px">Rank</th><th>Domain</th><th>Industry</th><th>Estimated Monthly Sales (USD)</th><th>Support Emails</th><th>Support Phone Number</th><th>City</th><th>Combined Social Media Followers</th></tr></thead><tbody><tr><td style="text-align:center;width:100px">1</td><td><a href="https://ghanayello.com" rel="noreferrer" target="_blank">ghanayello.com</a></td><td></td><td>$ 280,554</td><td></td><td><div class="tooltip"><span class="tooltip-body">+233 24 465 6909 and 1 more</span> <span class="tooltip-text">+233 30 225 2266</span></div></td><td>Accra</td><td>283</td></tr><tr><td style="text-align:center;width:100px">2</td><td><a href="https://fashionghana.com" rel="noreferrer" target="_blank">fashionghana.com</a></td><td>Clothing Broad</td><td>$ 272,595</td><td></td><td><div class="tooltip"><span class="tooltip-body">+233 20 202 2008 and 1 more</span> <span class="tooltip-text">+233 23 362 2008</span></div></td><td>Accra</td><td>1,174,649</td></tr><tr><td style="text-align:center;width:100px">3</td><td><a href="https://deus.com.gh" rel="noreferrer" target="_blank">deus.com.gh</a></td><td><div class="tooltip"><span class="tooltip-body">Office Accessories and 1 more</span> <span class="tooltip-text">Computer Hardware</span></div></td><td>$ 201,262</td><td><a class="__cf_email__" data-cfemail="b0c3d1dcd5c3f0d4d5c5c39ed3dfdd9ed7d8" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 30 243 7082 and 2 more</span> <span class="tooltip-text">+233 55 972 2669,<br/>+233 30 242 2666</span></div></td><td></td><td>38,012</td></tr><tr><td style="text-align:center;width:100px">4</td><td><a href="https://compughana.com" rel="noreferrer" target="_blank">compughana.com</a></td><td>Home Repair &amp; Construction</td><td>$ 195,919</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="b9d0d7dfd6f9dad6d4c9ccded1d8d7d897dad6d4" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="f182909d9482b1929e9c81849699909f90df929e9c" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 30 275 2020</td><td>Accra</td><td>420,207</td></tr><tr><td style="text-align:center;width:100px">5</td><td><a href="https://ubuy.com.gh" rel="noreferrer" target="_blank">ubuy.com.gh</a></td><td></td><td>$ 190,290</td><td><a class="__cf_email__" data-cfemail="f0999e969fb085928589de939f9d" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td></td><td></td><td>6,073</td></tr><tr><td style="text-align:center;width:100px">6</td><td><a href="https://flyzipline.com" rel="noreferrer" target="_blank">flyzipline.com</a></td><td></td><td>$ 189,023</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="4a03243c2f393e2538390a282325243e2f2922642e2f" href="/cdn-cgi/l/email-protection">[email protected]</a> and 2 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="e8a58d8c8189a88a8187869c8d8b80c68c8d" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="2a474f4e434b6a4c465350435a4643444f04494547" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td></td><td></td><td>22,749</td></tr><tr><td style="text-align:center;width:100px">7</td><td><a href="https://sprogstore.com" rel="noreferrer" target="_blank">sprogstore.com</a></td><td><div class="tooltip"><span class="tooltip-body">Children's Apparel and 2 more</span> <span class="tooltip-text">Nursery &amp; Kids Room,<br/>Family Stores</span></div></td><td>$ 187,245</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="7f161119103f0c0f0d10180c0b100d1a511c1012" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="1360727f7660536063617c7460677c61763d707c7e" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td><div class="tooltip"><span class="tooltip-body">+233 50 118 1818 and 2 more</span> <span class="tooltip-text">+233 20 699 8633,<br/>+233 20 699 8636</span></div></td><td>Accra</td><td>12,045</td></tr><tr><td style="text-align:center;width:100px">8</td><td><a href="https://nakroteck.net" rel="noreferrer" target="_blank">nakroteck.net</a></td><td></td><td>$ 178,886</td><td><a class="__cf_email__" data-cfemail="85f6e4e9e0f6c5ebe4eef7eaf1e0e6eeabebe0f1" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 55 050 7788</td><td>Nii Okaiman East</td><td>10,814</td></tr><tr><td style="text-align:center;width:100px">9</td><td><a href="https://senetic.com.gh" rel="noreferrer" target="_blank">senetic.com.gh</a></td><td><div class="tooltip"><span class="tooltip-body">Computer Hardware and 1 more</span> <span class="tooltip-text">Multi Purpose Softwares</span></div></td><td>$ 178,884</td><td><a class="__cf_email__" data-cfemail="1871767e77586b7d767d6c717b367b7775367f70" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 50 728 4001 and 1 more</span> <span class="tooltip-text">+234 1 227 8969</span></div></td><td></td><td>4,672</td></tr><tr><td style="text-align:center;width:100px">10</td><td><a href="https://whogohost.com.gh" rel="noreferrer" target="_blank">whogohost.com.gh</a></td><td></td><td>$ 171,107</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="760503060619040236011e1911191e1905025815191b" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="6f0d0603030601082f180700080007001c1b410c0002" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td></td><td></td><td>28,065</td></tr><tr><td style="text-align:center;width:100px">11</td><td><a href="https://plendify.com" rel="noreferrer" target="_blank">plendify.com</a></td><td></td><td>$ 170,272</td><td><a class="__cf_email__" data-cfemail="8be2e5ede4cbfbe7eee5efe2edf2a5e8e4e6" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+1 888-904-2349 and 1 more</span> <span class="tooltip-text">+233 54 013 2227</span></div></td><td></td><td>281</td></tr><tr><td style="text-align:center;width:100px">12</td><td><a href="https://lukinsdonkomi.com" rel="noreferrer" target="_blank">lukinsdonkomi.com</a></td><td></td><td>$ 167,958</td><td><a class="__cf_email__" data-cfemail="5e373038311e322b3537302d3a313035313337703d3133" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 20 840 2836</td><td>Takoradi</td><td>14,187</td></tr><tr><td style="text-align:center;width:100px">13</td><td><a href="https://telesol4g.com" rel="noreferrer" target="_blank">telesol4g.com</a></td><td>Consumer Electronics</td><td>$ 160,787</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="c6a3a8b7b3afb4bf86b2a3aaa3b5a9aaf2a1e8a5a9ab" href="/cdn-cgi/l/email-protection">[email protected]</a> and 4 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="bddbc9c9d5cedcd1d8cefdc9d8d1d8ced2d189da93ded2d0" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="d7b6a7a7bbbeb4b6a3beb8b9a497a3b2bbb2a4b8bbe3b0f9b4b8ba" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="7a190f090e15171f08191b081f3a0e1f161f0915164e1d54191517" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="5023313c35231024353c35233f3c64377e333f3d" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 30 397 5342</td><td>Accra</td><td>24,021</td></tr><tr><td style="text-align:center;width:100px">14</td><td><a href="https://fashionpivot.com" rel="noreferrer" target="_blank">fashionpivot.com</a></td><td>Clothing Broad</td><td>$ 156,654</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="fc9a9d8f949593928c958a9388bc9b919d9590d29f9391" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="3950575f56795f584a5150565749504f564d175a5654" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 27 177 0010</td><td></td><td>35,397</td></tr><tr><td style="text-align:center;width:100px">15</td><td><a href="https://jbklutse.com" rel="noreferrer" target="_blank">jbklutse.com</a></td><td>Consumer Electronics</td><td>$ 156,588</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="d8b1b6beb798b2bab3b4adacabbdf6bbb7b5" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="57243f3827173d353c3b222324327934383a" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 27 283 9333</td><td>Accra</td><td>343,192</td></tr><tr><td style="text-align:center;width:100px">16</td><td><a href="https://ebitcoinics.com" rel="noreferrer" target="_blank">ebitcoinics.com</a></td><td></td><td>$ 156,286</td><td><a class="__cf_email__" data-cfemail="0f476a637f4f6a4d667b6c606661666c7c216c6062" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 24 450 6564 and 1 more</span> <span class="tooltip-text">+233 55 069 7850</span></div></td><td>Kumasi</td><td>6,458</td></tr><tr><td style="text-align:center;width:100px">17</td><td><a href="https://adinkradesigns.co" rel="noreferrer" target="_blank">adinkradesigns.co</a></td><td>Toys</td><td>$ 156,037</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="e68e838a8a89a687828f888d94878283958f818895c88589" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="a5cdc0c9c9cae5c4c1cccbced7c4c1c0d6ccc2cbd68bc6cac88bc4d0" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td><div class="tooltip"><span class="tooltip-body">+233 24 154 6969 and 1 more</span> <span class="tooltip-text">+233 24 350 4975</span></div></td><td></td><td>5,418</td></tr><tr><td style="text-align:center;width:100px">18</td><td><a href="https://decathlon.com.gh" rel="noreferrer" target="_blank">decathlon.com.gh</a></td><td><div class="tooltip"><span class="tooltip-body">Activewear and 2 more</span> <span class="tooltip-text">Footwear,<br/>Sporting Goods</span></div></td><td>$ 155,552</td><td><a class="__cf_email__" data-cfemail="2d4e4243594c4e59034a454c434c6d49484e4c5945414243034e4240" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 50 599 9070</td><td></td><td>48,470</td></tr><tr><td style="text-align:center;width:100px">19</td><td><a href="https://bestpricegh.com" rel="noreferrer" target="_blank">bestpricegh.com</a></td><td>Video Games &amp; Accessories</td><td>$ 154,947</td><td><a class="__cf_email__" data-cfemail="fc95929a93bc9e998f888c8e959f999b94d29f9391" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 24 633 0667</td><td>Accra</td><td>48,555</td></tr><tr><td style="text-align:center;width:100px">20</td><td><a href="https://hiphopafrica.net" rel="noreferrer" target="_blank">hiphopafrica.net</a></td><td></td><td>$ 154,947</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="84e5e0f2e1f6f0edf7edeae3c4ecedf4ecebf4e5e2f6ede7e5aaeae1f0" href="/cdn-cgi/l/email-protection">[email protected]</a> and 2 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="bad3d4dcd5fad2d3cad2d5cadbdcc8d3d9db94d4dfce" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="462c292435062e2f362e29362720342f252768282332" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 30 263 3210</td><td></td><td>6,440</td></tr><tr><td style="text-align:center;width:100px">21</td><td><a href="https://atcmask.com" rel="noreferrer" target="_blank">atcmask.com</a></td><td></td><td>$ 153,857</td><td><a class="__cf_email__" data-cfemail="d4b7bbbaa0b5b7a094b5a0b7b9b5a7bffab7bbb9" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 30 290 7689 and 1 more</span> <span class="tooltip-text">+233 55 957 8355</span></div></td><td>Accra</td><td>10,197</td></tr><tr><td style="text-align:center;width:100px">22</td><td><a href="https://ovationhall.com" rel="noreferrer" target="_blank">ovationhall.com</a></td><td></td><td>$ 152,311</td><td></td><td></td><td></td><td>5,476</td></tr><tr><td style="text-align:center;width:100px">23</td><td><a href="https://visitghana.com" rel="noreferrer" target="_blank">visitghana.com</a></td><td></td><td>$ 151,074</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="2d44434b426d5b445e44594a454c434c034e4240" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="aac3c4ccc5eacdc2cbc4cb84ded8cbdccfc6" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td><div class="tooltip"><span class="tooltip-body">+233 30 700 7100 and 3 more</span> <span class="tooltip-text">+233 50 949 7700,<br/>+233 55 843 9868,<br/>+233 24 040 2408</span></div></td><td></td><td>49,512</td></tr><tr><td style="text-align:center;width:100px">24</td><td><a href="https://whoopro.com" rel="noreferrer" target="_blank">whoopro.com</a></td><td></td><td>$ 149,914</td><td><a class="__cf_email__" data-cfemail="03676a646a77626f43746b6c6c73716c2d606c6e" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 30 291 2071</td><td></td><td>8,099</td></tr><tr><td style="text-align:center;width:100px">25</td><td><a href="https://aftown.com" rel="noreferrer" target="_blank">aftown.com</a></td><td></td><td>$ 147,774</td><td><a class="__cf_email__" data-cfemail="1665636666796462567770627961783875797b" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 55 589 2892</td><td>Accra</td><td>40,835</td></tr><tr><td style="text-align:center;width:100px">26</td><td><a href="https://sheqxel.com" rel="noreferrer" target="_blank">sheqxel.com</a></td><td>Multi Purpose Softwares</td><td>$ 147,774</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="e1888f878ea19289849099848dcf828e8c" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="582b2d2828372a2c182b303d29203d34763b3735" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td></td><td>Accra</td><td>1,208</td></tr><tr><td style="text-align:center;width:100px">27</td><td><a href="https://gacl.com.gh" rel="noreferrer" target="_blank">gacl.com.gh</a></td><td></td><td>$ 147,200</td><td><a class="__cf_email__" data-cfemail="026b6c646d426563616e2c616d6f2c656a" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 30 255 0612 and 2 more</span> <span class="tooltip-text">+233 30 296 1975,<br/>+233 54 433 4024</span></div></td><td></td><td>56,240</td></tr><tr><td style="text-align:center;width:100px">28</td><td><a href="https://electrolandgh.com" rel="noreferrer" target="_blank">electrolandgh.com</a></td><td><div class="tooltip"><span class="tooltip-body">Home Appliances and 1 more</span> <span class="tooltip-text">Home Furnishing &amp; Decoration</span></div></td><td>$ 146,509</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="046d6a626b4461686167706b7668656a60636c2a676b69" href="/cdn-cgi/l/email-protection">[email protected]</a> and 2 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="e48d8a828ba48188818790968b88858a80838cca878b89" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="afdccec3cadcefcac3caccdbddc0c3cec1cbc8c781ccc0c2" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td><div class="tooltip"><span class="tooltip-body">+233 24 243 9437 and 2 more</span> <span class="tooltip-text">+233 30 221 1318,<br/>+233 30 281 7555</span></div></td><td>Accra</td><td>198,743</td></tr><tr><td style="text-align:center;width:100px">29</td><td><a href="https://kaetechdigital.com" rel="noreferrer" target="_blank">kaetechdigital.com</a></td><td></td><td>$ 146,457</td><td></td><td>+86 156 6511 2952</td><td>Accra</td><td>4,326</td></tr><tr><td style="text-align:center;width:100px">30</td><td><a href="https://goodluckafrica.com" rel="noreferrer" target="_blank">goodluckafrica.com</a></td><td>Clothing Broad</td><td>$ 146,164</td><td><a class="__cf_email__" data-cfemail="254c4b434a65424a4a414950464e4443574c46440b464a48" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td><div class="tooltip"><span class="tooltip-body">+233 20 439 1011 and 1 more</span> <span class="tooltip-text">+233 30 707 2121</span></div></td><td>Accra</td><td>256,686</td></tr><tr><td style="text-align:center;width:100px">31</td><td><a href="https://extratimeonline.com" rel="noreferrer" target="_blank">extratimeonline.com</a></td><td>Sporting Goods</td><td>$ 145,474</td><td><a class="__cf_email__" data-cfemail="6a0f121e180b1e03070f05040603040f2a130b09070f0e030b1a18050e1f091e0305041944090507" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td></td><td>Accra</td><td>1,015</td></tr><tr><td style="text-align:center;width:100px">32</td><td><a href="https://starlite.com.gh" rel="noreferrer" target="_blank">starlite.com.gh</a></td><td>Computer Hardware</td><td>$ 145,474</td><td><a class="__cf_email__" data-cfemail="5b283a373e281b282f3a2937322f3e75383436753c33" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td>+233 24 090 0600</td><td>Accra</td><td>99,163</td></tr><tr><td style="text-align:center;width:100px">33</td><td><a href="https://aaksonline.com" rel="noreferrer" target="_blank">aaksonline.com</a></td><td>Fashion Accessories</td><td>$ 139,996</td><td><a class="__cf_email__" data-cfemail="e58c8b838aa584848e968a8b898c8b80cb868a88" href="/cdn-cgi/l/email-protection">[email protected]</a></td><td></td><td>Kumasi</td><td>4,702</td></tr><tr><td style="text-align:center;width:100px">34</td><td><a href="https://wopedigital.com" rel="noreferrer" target="_blank">wopedigital.com</a></td><td></td><td>$ 139,996</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="6112000d041221160e11040508060815000d4f020e0c" href="/cdn-cgi/l/email-protection">[email protected]</a> and 1 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="70191e161f30071f00151419171904111c5e131f1d" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td>+233 24 399 6025</td><td></td><td>15,295</td></tr><tr><td style="text-align:center;width:100px">35</td><td><a href="https://palacestores.com" rel="noreferrer" target="_blank">palacestores.com</a></td><td></td><td>$ 139,666</td><td><div class="tooltip"><span class="tooltip-body"><a class="__cf_email__" data-cfemail="4d2223212423280d3d2c212c2e283e39223f283e632e2220" href="/cdn-cgi/l/email-protection">[email protected]</a> and 2 more</span> <span class="tooltip-text"><a class="__cf_email__" data-cfemail="731c01171601003303121f12101600071c0116005d101c1e" href="/cdn-cgi/l/email-protection">[email protected]</a>,<br/><a class="__cf_email__" data-cfemail="8acecfc6c3dccfd8d3cadacbc6cbc9cfd9dec5d8cfd9a4c9c5c7" href="/cdn-cgi/l/email-protection">[email protected]</a></span></div></td><td><div class="toolt

In [ ]:
soup.find_all('th')
ecom = soup.find_all('th')

In [ ]:
ecom

[<th id="rank" style="width:100px">Rank</th>,
 <th>Domain</th>,
 <th>Industry</th>,
 <th>Estimated Monthly Sales (USD)</th>,
 <th>Support Emails</th>,
 <th>Support Phone Number</th>,
 <th>City</th>,
 <th>Combined Social Media Followers</th>]

In [ ]:
ecom_title = [title.text for title in ecom]

In [ ]:
print(ecom_title)

['Rank', 'Domain', 'Industry', 'Estimated Monthly Sales (USD)', 'Support Emails', 'Support Phone Number', 'City', 'Combined Social Media Followers']

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(columns = ecom_title)

df

Empty DataFrame
Columns: [Rank, Domain, Industry, Estimated Monthly Sales (USD), Support Emails, Support Phone Number, City, Combined Social Media Followers]
Index: []

In [ ]:
column_data = soup.find_all('tr')

In [ ]:
for row in column_data [1:]:
    row_data = row.find_all('td')
    individual_data = [data.text for data in row_data]


    length = len(df)
    df.loc[length] = individual_data

In [ ]:
df

,Rank,Domain,Industry,Estimated Monthly Sales (USD),Support Emails,Support Phone Number,City,Combined Social Media Followers
0,1003,dwellgh.com,,"$ 9,159",[email protected],,Accra,198
1,1,ghanayello.com,,"$ 280,554",,+233 24 465 6909 and 1 more +233 30 225 2266,Accra,283
2,2,fashionghana.com,Clothing Broad,"$ 272,595",,+233 20 202 2008 and 1 more +233 23 362 2008,Accra,"1,174,649"
3,3,deus.com.gh,Office Accessories and 1 more Computer Hardware,"$ 201,262",[email protected],"+233 30 243 7082 and 2 more +233 55 972 2669,+...",,"38,012"
4,4,compughana.com,Home Repair & Construction,"$ 195,919",[email protected] and 1 more [email protected],+233 30 275 2020,Accra,"420,207"
...,...,...,...,...,...,...,...,...
999,999,slce.edu.gh,,"$ 9,163",[email protected],+233 24 461 4631 and 1 more +233 32 202 8081,,103
1000,1000,dwellgh.com,,"$ 9,159",[email protected],,Accra,198
1001,1001,dwellgh.com,,"$ 9,159",[email protected],,Accra,198
1002,1002,dwellgh.com,,"$ 9,159",[email protected],,Accra,198
1003,1003,dwellgh.com,,"$ 9,159",[email protected],,Accra,198

In [ ]:
df = df.drop(['Rank','Support Emails','City','Support Phone Number'], axis = 1)

In [ ]:
df

,Domain,Industry,Estimated Monthly Sales (USD),Combined Social Media Followers
0,dwellgh.com,,"$ 9,159",198
1,ghanayello.com,,"$ 280,554",283
2,fashionghana.com,Clothing Broad,"$ 272,595","1,174,649"
3,deus.com.gh,Office Accessories and 1 more Computer Hardware,"$ 201,262","38,012"
4,compughana.com,Home Repair & Construction,"$ 195,919","420,207"
...,...,...,...,...
999,slce.edu.gh,,"$ 9,163",103
1000,dwellgh.com,,"$ 9,159",198
1001,dwellgh.com,,"$ 9,159",198
1002,dwellgh.com,,"$ 9,159",198
1003,dwellgh.com,,"$ 9,159",198

In [ ]:
import os
output_dir = '/content/downloads/'
os.makedirs(output_dir, exist_ok=True)
df.to_csv(os.path.join(output_dir, 'E-com.csv'), index=False)

#Conclusion
The dataset i finally ended up with shows the trends of E-commerce companies and this dataset can be used to make practical business decisions or help those who want to break into E-commerce in Ghana, if analysed correctly

#Flaw
There is a flaw with this dataset which is that the null values are alot